[[pages]]
path = "app.py"
name = "å·¥ä½œæ•ˆç‡å¹³å°"
icon = "ğŸ­"

[[pages]]
path = "pages/1_é©—æ”¶é”æ¨™æ•ˆç‡.py"
name = "é©—æ”¶é”æ¨™æ•ˆç‡"
icon = "âœ…"

[[pages]]
path = "pages/2_ç¸½ä¸Šçµ„ä¸Šæ¶ç”¢èƒ½.py"
name = "ç¸½ä¸Šçµ„ä¸Šæ¶ç”¢èƒ½"
icon = "ğŸ“¦"
